spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: tcc-transaction-http-order
  freemarker:
    template-loader-path: classpath:/ftl/
    suffix: .ftl
    settings:
      template_update_delay: 5
      default_encoding: UTF-8
      locale: UTF-8
      datetime_format: yyyy-MM-dd HH:mm:ss
      time_format: HH:mm:ss
      number_format: 0.####
      boolean_format: true,false
      whitespace_stripping: true
      tag_syntax: auto_detect
      url_escaping_charset: UTF-8
      classic_compatible: true
  tcc:
    recovery:
      #      max-retry-count: 30
      #      recover-duration: 30
      #      cron-expression: 0/15 * * * * ?
      #      fetch-page-size: 200
      #      concurrent-recovery-thread-count: 10
      recovery-enabled: false
    storage:
      storage-type: remoting
      domain: "TCC:FEIGN:ORDER"
    #      location: /tmp/${spring.tcc.storage.domain}
    #      serializer-type: customized
    #      transaction-serializer-class-name: org.mengyun.tcctransaction.serializer.json.JacksonTransactionSerializer
    #      max-transaction-size: 100000
    #      storage-mode: central
    #      shard-redis: # 测试ok
    #        nodes:
    #          - host: 127.0.0.1
    #            port: 16379
    #          - host: 127.0.0.1
    #            port: 16380
    #          - host: 127.0.0.1
    #            port: 16381
    registry:
      registry-type: direct
      cluster-name: default
      direct:
        server-addresses: 127.0.0.1:2332
#      zookeeper:
#        connect-string: 127.0.0.1:2181
#        max-retries: 4
#      nacos:
#        server-addr: 127.0.0.1:8848
server:
  port: 8081
